name: Release PR

on:
  push:
    branches:
      - main
  workflow_dispatch: # for manual release fixes
    inputs:
      retry-publish:
        description: "Retry publishing"
        type: boolean
        required: false
        default: false

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses:  block/ospo/actions/releaser@leordev/ospo-releaser-app
        with:
          release-type: node
          node-version: 20
          block-releaser-app-id: ${{ secrets.BLOCK_RELEASER_APP_ID }}
          block-releaser-private-key: ${{ secrets.BLOCK_RELEASER_APP_PRIVATE_KEY }}
          npm-token: ${{ secrets.NPM_TOKEN }}
          package-manager: yarn
          retry-publish: ${{ inputs.retry-publish }}
          prepare-cmds: |
            yarn install --frozen-lockfile
            yarn lint
