name: Release PR

on:
  push:
    branches:
      - main
  workflow_dispatch: # for manual release fixes

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: leordev/gha-sandbox/releaser@main
        with:
          release-type: node
          node-version: 20
          npm-token: ${{ secrets.NPM_TOKEN }}
          package-manager: yarn
          prepare-cmds: |
            yarn install --frozen-lockfile
            yarn lint
