name: "Release Linter PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: leordev/gha-sandbox/releaser-linter@main
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}